### PR TITLE
Update README.md

### LINKED ISSUE #8: Create a good README
We need a README that tells people who are contributing how to set up Nimbus. It should include:

- A logo for the repo
- "What This Includes" Section
- "Getting Started" Section
- The "Getting Started" Section should have several sub-sections: 
- "Requirements" 
- "Quick Start"
- "Starting from Scratch"
"Troubleshooting"

Try to keep it to this order unless there's folks think there's a better order

### PR DESCRIPTION
**Pull request by ay-a-git**
Fixes #8

### CODE REVIEW

**Comment by Lito-Frito** [comment]
@ay-a-git can you confirm that the README makes sense? I used an old Gatsby project as a template.

Also, lmk if you hate the logo. It can just be a stand-in for now, but if you hate it, lmk. And lmk any questions you have.

If everything is good, I'll approve the PR

**Review by ay-a-git — COMMENTED** [review]
ok here they are. I see them now. Don't like them at all but its a start

**Review by ay-a-git — COMMENTED** [review]
the tagline is nice though. I like it

**Comment by Lito-Frito** [comment]
> the tagline is nice though. I like it

Thank you, I tried my best to make the name make sense with the goal/service

**Comment by Lito-Frito** [comment]
> ok here they are. I see them now. Don't like them at all but its a start

The logos? What don't you like? Color? Font? I can still change some things

**Comment by Lito-Frito** [comment]
> @ay-a-git can you confirm that the README makes sense? I used an old Gatsby project as a template.
> 
> Also, lmk if you hate the logo. It can just be a stand-in for now, but if you hate it, lmk. And lmk any questions you have.
> 
> If everything is good, I'll approve the PR

@ay-a-git also this ^

**Comment by Lito-Frito** [comment]
@ay-a-git please confirm if the instructions on the README are accurate. Also, lmk what exactly you didn't like (e.g. the README, logos, etc)

**Comment by Lito-Frito** [comment]
> @ay-a-git please confirm if the instructions on the README are accurate. Also, lmk what exactly you didn't like (e.g. the README, logos, etc)

Once confirmed, I'll rebase & merge

**Review by Lito-Frito — DISMISSED** [review]

**Review by Lito-Frito — APPROVED** [review]

**Pull request merged**
