### PR TITLE
Time capsule timer

### LINKED ISSUE #6: Create a Prototype to the Time Capusle Function
Create a timer which returns messages to the console

### PR DESCRIPTION
**Pull request by ay-a-git**
Fixes #6

### CODE REVIEW

**Review by Lito-Frito — COMMENTED** [review]
What's the diff between #3 & #4 ?

Also, there was a conflict in nimbusCBT/client/src/App.jsx . I tried to resolve it but please check me

**Comment by Lito-Frito** [comment]
@ay-a-git can you get back to my comments? Then I'll know whether to merge or not

**Comment by Lito-Frito** [comment]
@ay-a-git bump

**Comment by ay-a-git** [comment]
edited conflicts. If issues still arise they were unimportant anyways. 2 lines of code fixed.

**Review by Lito-Frito — APPROVED** [review]

**Pull request merged**
